name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake GIF and SVG
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: belalhanafy
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build
      - run: git status

      # Push changes to the repository (output branch)
      - name: Push changes
        uses: ad-m/github-push-action@v0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Ensure this is the correct output branch for GitHub Pages
          force: true

      # Deploy to GitHub Pages from the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
